/**
 * This file is part of libmsmcomm.
 *
 * (C) 2011 Simon Busch <morphis@gravedo.de>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA
 *
 **/

namespace Msmcomm.LowLevel
{
    public enum MessageType
    {
        INVALID,
        COMMAND_CALL_ORIGINATION,
        COMMAND_CALL_ANSWER,
        COMMAND_CALL_END,
        COMMAND_CALL_SUPS,

        COMMAND_STATE_CHANGE_OPERATION_MODE_REQUEST,

        COMMAND_MISC_TEST_ALIVE,
        COMMAND_MISC_GET_RADIO_FIRMWARE_VERSION,
        COMMAND_MISC_GET_CHARGER_STATUS,
        COMMAND_MISC_SET_CHARGE,
        COMMAND_MISC_SET_DATE,
        COMMAND_MISC_GET_IMEI,

        COMMAND_SIM_VERIFY_PIN,
        COMMAND_SIM_ENABLE_PIN,
        COMMAND_SIM_DISABLE_PIN,
        COMMAND_SIM_CHANGE_PIN,
        COMMAND_SIM_GET_SIM_CAPABILITIES,
        COMMAND_SIM_GET_ALL_PIN_STATUS_INFO,

        COMMAND_PHONEBOOK_READ_RECORD,
        COMMAND_PHONEBOOK_READ_RECORD_BULD,
        COMMAND_PHONEBOOK_WRITE_RECORD,
        COMMAND_PHONEBOOK_GET_ALL_RECORD_ID,
        COMMAND_PHONEBOOK_EXTENDED_FILE_INFO,

        RESPONSE_CALL_CALLBACK,
        RESPONSE_CALL_RETURN,

        RESPONSE_STATE_CALLBACK,

        RESPONSE_MISC_TEST_ALIVE,
        RESPONSE_MISC_GET_RADIO_FIRMWARE_VERSION,
        RESPONSE_MISC_GET_CHARGER_STATUS,
        RESPONSE_MISC_SET_CHARGE,
        RESPONSE_MISC_SET_DATE,
        RESPONSE_MISC_GET_IMEI,

        RESPONSE_SIM_CALLBACK,

        RESPONSE_PHONEBOOK_RETURN,

        UNSOLICITED_RESPONSE_STATE_OPRT_MODE,
        UNSOLICITED_RESPONSE_STATE_TEST_CONTROL_TYPE,
        UNSOLICITED_RESPONSE_STATE_SYS_SEL_PREF,
        UNSOLICITED_RESPONSE_STATE_ANSWER_VOICE,
        UNSOLICITED_RESPONSE_STATE_NAM_SEL,
        UNSOLICITED_RESPONSE_STATE_CURR_NAM,
        UNSOLICITED_RESPONSE_STATE_IN_USE_STATE,
        UNSOLICITED_RESPONSE_STATE_CDMA_LOCK_MODE,
        UNSOLICITED_RESPONSE_STATE_UZ_CHANGED,
        UNSOLICITED_RESPONSE_STATE_MAINTREQ,
        UNSOLICITED_RESPONSE_STATE_STANDBY_SLEEP,
        UNSOLICITED_RESPONSE_STATE_STANDBY_WAKE,
        UNSOLICITED_RESPONSE_STATE_INFO,
        UNSOLICITED_RESPONSE_STATE_PACKET_STATE,
        UNSOLICITED_RESPONSE_STATE_INFO_AVAIL,
        UNSOLICITED_RESPONSE_STATE_SUBSCRIPTION_AVAILABLE,
        UNSOLICITED_RESPONSE_STATE_SUBSCRIPTION_NOT_AVAILABLE,
        UNSOLICITED_RESPONSE_STATE_SUBSCRIPTION_CHANGED,
        UNSOLICITED_RESPONSE_STATE_AVAILABLE_NETWORKS_CONF,
        UNSOLICITED_RESPONSE_STATE_PREFERRED_NETWORKS_CONF,
        UNSOLICITED_RESPONSE_STATE_FUNDS_LOW,
        UNSOLICITED_RESPONSE_STATE_WAKEUP_FROM_STANDBY,
        UNSOLICITED_RESPONSE_STATE_NVRUIM_CONFIG_CHANGED,
        UNSOLICITED_RESPONSE_STATE_PREFERRED_NETWORKS_SET,
        UNSOLICITED_RESPONSE_STATE_DDTM_PREF,
        UNSOLICITED_RESPONSE_STATE_PS_ATTACH_FAILED,
        UNSOLICITED_RESPONSE_STATE_RESET_ACM_COMPLETED,
        UNSOLICITED_RESPONSE_STATE_SET_ACMMAX_COMPLETED,
        UNSOLICITED_RESPONSE_STATE_CDMA_CAPABILITY_UPDATED,
        UNSOLICITED_RESPONSE_STATE_LINE_SWITCHING,
        UNSOLICITED_RESPONSE_STATE_SELECTED_LINE,
        UNSOLICITED_RESPONSE_STATE_SECONDARY_MSM,
        UNSOLICITED_RESPONSE_STATE_TERMINATE_GET_NETWORKS,
        UNSOLICITED_RESPONSE_STATE_DDTM_STATUS,
        UNSOLICITED_RESPONSE_STATE_CCBS_STORE_INFO_CHANGED,
        UNSOLICITED_RESPONSE_STATE_EVENT_UNFORCE_ORIG_COMPLETE,
        UNSOLICITED_RESPONSE_STATE_SEND_MANUAL_NET_SELECTN,

        UNSOLICITED_RESPONSE_MISC_RADIO_RESET_IND,
        UNSOLICITED_RESPONSE_MISC_CHARGER_STATUS,

        UNSOLICITED_RESPONSE_SIM_SIM_INSERTED,
        UNSOLICITED_RESPONSE_SIM_SIM_REMOVED,
        UNSOLICITED_RESPONSE_SIM_DRIVER_ERROR,
        UNSOLICITED_RESPONSE_SIM_CARD_ERROR,
        UNSOLICITED_RESPONSE_SIM_MEMORY_WARNING,
        UNSOLICITED_RESPONSE_SIM_NO_SIM_EVENT,
        UNSOLICITED_RESPONSE_SIM_NO_SIM,
        UNSOLICITED_RESPONSE_SIM_SIM_INIT_COMPLETED,
        UNSOLICITED_RESPONSE_SIM_SIM_INIT_COMPLETED_NO_PROV,
        UNSOLICITED_RESPONSE_SIM_PIN1_VERIFIED,
        UNSOLICITED_RESPONSE_SIM_PIN1_BLOCKED,
        UNSOLICITED_RESPONSE_SIM_PIN1_UNBLOCKED,
        UNSOLICITED_RESPONSE_SIM_PIN1_ENABLED,
        UNSOLICITED_RESPONSE_SIM_PIN1_DISABLED,
        UNSOLICITED_RESPONSE_SIM_PIN1_CHANGED,
        UNSOLICITED_RESPONSE_SIM_PIN1_PERM_BLOCKED,
        UNSOLICITED_RESPONSE_SIM_PIN2_VERIFIED,
        UNSOLICITED_RESPONSE_SIM_PIN2_BLOCKED,
        UNSOLICITED_RESPONSE_SIM_PIN2_UNBLOCKED,
        UNSOLICITED_RESPONSE_SIM_PIN2_ENABLED,
        UNSOLICITED_RESPONSE_SIM_PIN2_DISABLED,
        UNSOLICITED_RESPONSE_SIM_PIN2_CHANGED,
        UNSOLICITED_RESPONSE_SIM_PIN2_PERM_BLOCKED,
        UNSOLICITED_RESPONSE_SIM_NO_EVENT,
        UNSOLICITED_RESPONSE_SIM_OK_FOR_TERMINAL_PROFILE_DL,
        UNSOLICITED_RESPONSE_SIM_NOT_OK_FOR_TERMINAL_PROFILE_DL,
        UNSOLICITED_RESPONSE_SIM_REFRESH_SIM_RESET,
        UNSOLICITED_RESPONSE_SIM_REFRESH_SIM_INIT,
        UNSOLICITED_RESPONSE_SIM_FDN_ENABLE,
        UNSOLICITED_RESPONSE_SIM_FDN_DISABLE,
        UNSOLICITED_RESPONSE_SIM_SIM_INSERTED_2,
        UNSOLICITED_RESPONSE_SIM_SIM_REMOVED_2,
        UNSOLICITED_RESPONSE_SIM_CARD_ERROR_2,
        UNSOLICITED_RESPONSE_SIM_MEMORY_WARNING_2,
        UNSOLICITED_RESPONSE_SIM_NO_SIM_EVENT_2,
        UNSOLICITED_RESPONSE_SIM_SIM_INIT_COMPLETED_2,
        UNSOLICITED_RESPONSE_SIM_SIM_INIT_COMPLETED_NO_PROV_2,
        UNSOLICITED_RESPONSE_SIM_PIN1_VERIFIED_2,
        UNSOLICITED_RESPONSE_SIM_PIN1_BLOCKED_2,
        UNSOLICITED_RESPONSE_SIM_PIN1_UNBLOCKED_2,
        UNSOLICITED_RESPONSE_SIM_PIN1_ENABLED_2,
        UNSOLICITED_RESPONSE_SIM_PIN1_DISABLED_2,
        UNSOLICITED_RESPONSE_SIM_PIN1_CHANGED_2,
        UNSOLICITED_RESPONSE_SIM_PIN1_PERM_BLOCKED_2,
        UNSOLICITED_RESPONSE_SIM_PIN2_VERIFIED_2,
        UNSOLICITED_RESPONSE_SIM_PIN2_BLOCKED_2,
        UNSOLICITED_RESPONSE_SIM_PIN2_UNBLOCKED_2,
        UNSOLICITED_RESPONSE_SIM_PIN2_ENABLED_2,
        UNSOLICITED_RESPONSE_SIM_PIN2_DISABLED_2,
        UNSOLICITED_RESPONSE_SIM_PIN2_CHANGED_2,
        UNSOLICITED_RESPONSE_SIM_PIN2_PERM_BLOCKED_2,
        UNSOLICITED_RESPONSE_SIM_REFRESH_SIM_RESET_2,
        UNSOLICITED_RESPONSE_SIM_REFRESH_SIM_INIT_2,
        UNSOLICITED_RESPONSE_SIM_FDN_ENABLE_2,
        UNSOLICITED_RESPONSE_SIM_FDN_DISABLE_2,
        UNSOLICITED_RESPONSE_SIM_OK_FOR_TERMINAL_PROFILE_DL_2,
        UNSOLICITED_RESPONSE_SIM_NOT_OK_FOR_TERMINAL_PROFILE_DL_2,
        UNSOLICITED_RESPONSE_SIM_REFRESH_SIM_INIT_FCN,
        UNSOLICITED_RESPONSE_SIM_REFRESH_SIM_INIT_FCN_2,
        UNSOLICITED_RESPONSE_SIM_REFRESH_FCN,
        UNSOLICITED_RESPONSE_SIM_REFRESH_FCN_2,
        UNSOLICITED_RESPONSE_SIM_REFRESH_FAILED,
        UNSOLICITED_RESPONSE_SIM_START_SWITCH_SLOT,
        UNSOLICITED_RESPONSE_SIM_FINISH_SWITCH_SLOT,
        UNSOLICITED_RESPONSE_SIM_PERSO_INIT_COMPLETED,
        UNSOLICITED_RESPONSE_SIM_PERSO_EVENT_GEN_PROP1,
        UNSOLICITED_RESPONSE_SIM_SIM_ILLEGAL,
        UNSOLICITED_RESPONSE_SIM_SIM_ILLEGAL_2,
        UNSOLICITED_RESPONSE_SIM_SIM_UHZI_V2_COMPLETE,
        UNSOLICITED_RESPONSE_SIM_SIM_UHZI_V1_COMPLETE,
        UNSOLICITED_RESPONSE_SIM_PERSO_EVENT_GEN_PROP2,
        UNSOLICITED_RESPONSE_SIM_INTERNAL_SIM_RESET,
        UNSOLICITED_RESPONSE_SIM_CARD_ERR_POLL_ERROR,
        UNSOLICITED_RESPONSE_SIM_CARD_ERR_NO_ATR_RECEIVED_WITH_MAX_VOLTAGE,
        UNSOLICITED_RESPONSE_SIM_CARD_ERR_NO_ATR_RECEIVED_AFTER_INT_RESET,
        UNSOLICITED_RESPONSE_SIM_CARD_ERR_CORRUPT_ATR_RCVD_MAX_TIMES,
        UNSOLICITED_RESPONSE_SIM_CARD_ERR_PPS_TIMED_OUT_MAX_TIMES,
        UNSOLICITED_RESPONSE_SIM_CARD_ERR_VOLTAGE_MISMATCH,
        UNSOLICITED_RESPONSE_SIM_CARD_ERR_INT_CMD_TIMED_OUT_AFTER_PPS,
        UNSOLICITED_RESPONSE_SIM_CARD_ERR_INT_CMD_ERR_EXCEED_MAX_ATTEMPTS,
        UNSOLICITED_RESPONSE_SIM_CARD_ERR_MAXED_PARITY_ERROR,
        UNSOLICITED_RESPONSE_SIM_CARD_ERR_MAXED_RX_BREAK_ERROR,
        UNSOLICITED_RESPONSE_SIM_CARD_ERR_MAXED_OVERRUN_ERROR,
        UNSOLICITED_RESPONSE_SIM_CARD_ERR_TRANSACTION_TIMER_EXPIRED,
        UNSOLICITED_RESPONSE_SIM_CARD_ERR_POWER_DOWN_CMD_NOTIFICATION,
        UNSOLICITED_RESPONSE_SIM_CARD_ERR_INT_CMD_ERR_IN_PASSIVE_MODE,
        UNSOLICITED_RESPONSE_SIM_CARD_ERR_CMD_TIMED_OUT_IN_PASSIVE_MODE,
        UNSOLICITED_RESPONSE_SIM_CARD_ERR_MAX_PARITY_IN_PASSIVE,
        UNSOLICITED_RESPONSE_SIM_CARD_ERR_MAX_RXBRK_IN_PASSIVE,
        UNSOLICITED_RESPONSE_SIM_CARD_ERR_MAX_OVERRUN_IN_PASSIVE,
        UNSOLICITED_RESPONSE_SIM_CARD_ERR_POLL_ERROR_2,
        UNSOLICITED_RESPONSE_SIM_CARD_ERR_NO_ATR_RECEIVED_WITH_MAX_VOLTAGE_2,
        UNSOLICITED_RESPONSE_SIM_CARD_ERR_NO_ATR_RECEIVED_AFTER_INT_RESET_2,
        UNSOLICITED_RESPONSE_SIM_CARD_ERR_CORRUPT_ATR_RCVD_MAX_TIMES_2,
        UNSOLICITED_RESPONSE_SIM_CARD_ERR_PPS_TIMED_OUT_MAX_TIMES_2,
        UNSOLICITED_RESPONSE_SIM_CARD_ERR_VOLTAGE_MISMATCH_2,
        UNSOLICITED_RESPONSE_SIM_CARD_ERR_INT_CMD_TIMED_OUT_AFTER_PPS_2,
        UNSOLICITED_RESPONSE_SIM_CARD_ERR_INT_CMD_ERR_EXCEED_MAX_ATTEMPTS_2,
        UNSOLICITED_RESPONSE_SIM_CARD_ERR_MAXED_PARITY_ERROR_2,
        UNSOLICITED_RESPONSE_SIM_CARD_ERR_MAXED_RX_BREAK_ERROR_2,
        UNSOLICITED_RESPONSE_SIM_CARD_ERR_MAXED_OVERRUN_ERROR_2,
        UNSOLICITED_RESPONSE_SIM_CARD_ERR_TRANSACTION_TIMER_EXPIRED_2,
        UNSOLICITED_RESPONSE_SIM_CARD_ERR_POWER_DOWN_CMD_NOTIFICATION_2,
        UNSOLICITED_RESPONSE_SIM_CARD_ERR_INT_CMD_ERR_IN_PASSIVE_MODE_2,
        UNSOLICITED_RESPONSE_SIM_CARD_ERR_CMD_TIMED_OUT_IN_PASSIVE_MODE_2,
        UNSOLICITED_RESPONSE_SIM_CARD_ERR_MAX_PARITY_IN_PASSIVE_2,
        UNSOLICITED_RESPONSE_SIM_CARD_ERR_MAX_RXBRK_IN_PASSIVE_2,
        UNSOLICITED_RESPONSE_SIM_CARD_ERR_MAX_OVERRUN_IN_PASSIVE_2,
        UNSOLICITED_RESPONSE_SIM_REFRESH_APP_RESET,
        UNSOLICITED_RESPONSE_SIM_REFRESH_3G_SESSION_RESET,
        UNSOLICITED_RESPONSE_SIM_REFRESH_APP_RESET_2,
        UNSOLICITED_RESPONSE_SIM_REFRESH_3G_SESSION_RESET_2,
        UNSOLICITED_RESPONSE_SIM_APP_SELECTED,
        UNSOLICITED_RESPONSE_SIM_APP_SELECTED_2,
        UNSOLICITED_RESPONSE_SIM_PERSO_NW_FAILURE,
        UNSOLICITED_RESPONSE_SIM_PERSO_NS_FAILURE,
        UNSOLICITED_RESPONSE_SIM_PERSO_SP_FAILURE,
        UNSOLICITED_RESPONSE_SIM_PERSO_CP_FAILURE,
        UNSOLICITED_RESPONSE_SIM_PERSO_SIM_FAILURE,
        UNSOLICITED_RESPONSE_SIM_PERSO_NW_DEACTIVATED,
        UNSOLICITED_RESPONSE_SIM_PERSO_NS_DEACTIVATED,
        UNSOLICITED_RESPONSE_SIM_PERSO_SP_DEACTIVATED,
        UNSOLICITED_RESPONSE_SIM_PERSO_CP_DEACTIVATED,
        UNSOLICITED_RESPONSE_SIM_PERSO_SIM_DEACTIVATED,
        UNSOLICITED_RESPONSE_SIM_PERSO_NCK_BLOCKED,
        UNSOLICITED_RESPONSE_SIM_PERSO_NSK_BLOCKED,
        UNSOLICITED_RESPONSE_SIM_PERSO_SPK_BLOCKED,
        UNSOLICITED_RESPONSE_SIM_PERSO_CCK_BLOCKED,
        UNSOLICITED_RESPONSE_SIM_PERSO_PPK_BLOCKED,
        UNSOLICITED_RESPONSE_SIM_PERSO_NCK_UNBLOCKED,
        UNSOLICITED_RESPONSE_SIM_PERSO_NSK_UNBLOCKED,
        UNSOLICITED_RESPONSE_SIM_PERSO_SPK_UNBLOCKED,
        UNSOLICITED_RESPONSE_SIM_PERSO_CCK_UNBLOCKED,
        UNSOLICITED_RESPONSE_SIM_PERSO_PPK_UNBLOCKED,
        UNSOLICITED_RESPONSE_SIM_PERSO_SANITY_ERROR,
        UNSOLICITED_RESPONSE_SIM_PERSO_GEN_PROP1,
        UNSOLICITED_RESPONSE_SIM_PERSO_GEN_PROP2,
        UNSOLICITED_RESPONSE_SIM_PERSO_EVT_INIT_COMPLETED,
        UNSOLICITED_RESPONSE_SIM_PLMN_SEL_MENU_ENABLE,
        UNSOLICITED_RESPONSE_SIM_PLMN_SEL_MENU_DISABLE,

        UNSOLICITED_RESPONSE_PHONEBOOK_RECORD_ADDED,
        UNSOLICITED_RESPONSE_PHONEBOOK_RECORD_UPDATED,
        UNSOLICITED_RESPONSE_PHONEBOOK_RECORD_DELETED,
        UNSOLICITED_RESPONSE_PHONEBOOK_RECORD_FAILED,
        UNSOLICITED_RESPONSE_PHONEBOOK_REFRESH_START,
        UNSOLICITED_RESPONSE_PHONEBOOK_REFRESH_DONE,
        UNSOLICITED_RESPONSE_PHONEBOOK_PHONEBOOK_READY,
        UNSOLICITED_RESPONSE_PHONEBOOK_LOCKED,
        UNSOLICITED_RESPONSE_PHONEBOOK_UNLOCKED,
        UNSOLICITED_RESPONSE_PHONEBOOK_PH_UNIQUE_IDS_VALIDATED,
        UNSOLICITED_RESPONSE_PHONEBOOK_RECORD_WRITE,
        UNSOLICITED_RESPONSE_PHONEBOOK_GET_ALL_RECORD_ID,
        UNSOLICITED_RESPONSE_PHONEBOOK_EXTENDED_FILE_INFO,
    }

    public string messageTypeToString(MessageType type)
    {
        string result = "UNKNOWN";

        switch (type)
        {
            case MessageType.INVALID:
                result = "INVALID";
                break;
            case MessageType.COMMAND_CALL_ORIGINATION:
                result = "COMMAND_CALL_ORIGINATION";
                break;
            case MessageType.COMMAND_CALL_ANSWER:
                result = "COMMAND_CALL_ANSWER";
                break;
            case MessageType.COMMAND_CALL_END:
                result = "COMMAND_CALL_END";
                break;
            case MessageType.COMMAND_CALL_SUPS:
                result = "COMMAND_CALL_SUPS";
                break;

            case MessageType.COMMAND_STATE_CHANGE_OPERATION_MODE_REQUEST:
                result = "COMMAND_STATE_CHANGE_OPERATION_MODE_REQUEST";
                break;

            case MessageType.COMMAND_MISC_TEST_ALIVE:
                result = "COMMAND_MISC_TEST_ALIVE";
                break;
            case MessageType.COMMAND_MISC_GET_RADIO_FIRMWARE_VERSION:
                result = "COMMAND_MISC_GET_RADIO_FIRMWARE_VERSION";
                break;
            case MessageType.COMMAND_MISC_GET_CHARGER_STATUS:
                result = "COMMAND_MISC_GET_CHARGER_STATUS";
                break;
            case MessageType.COMMAND_MISC_SET_CHARGE:
                result = "COMMAND_MISC_SET_CHARGE";
                break;
            case MessageType.COMMAND_MISC_SET_DATE:
                result = "COMMAND_MISC_SET_DATE";
                break;
            case MessageType.COMMAND_MISC_GET_IMEI:
                result = "COMMAND_MISC_GET_IMEI";
                break;

            case MessageType.COMMAND_SIM_VERIFY_PIN:
                result = "COMMAND_SIM_VERIFY_PIN";
                break;
            case MessageType.COMMAND_SIM_ENABLE_PIN:
                result = "COMMAND_SIM_ENABLE_PIN";
                break;
            case MessageType.COMMAND_SIM_DISABLE_PIN:
                result = "COMMAND_SIM_DISABLE_PIN";
                break;
            case MessageType.COMMAND_SIM_CHANGE_PIN:
                result = "COMMAND_SIM_CHANGE_PIN";
                break;
            case MessageType.COMMAND_SIM_GET_SIM_CAPABILITIES:
                result = "COMMAND_SIM_GET_SIM_CAPABILITIES";
                break;
            case MessageType.COMMAND_SIM_GET_ALL_PIN_STATUS_INFO:
                result = "COMMAND_SIM_GET_ALL_PIN_STATUS_INFO";
                break;

            case MessageType.COMMAND_PHONEBOOK_READ_RECORD:
                result = "COMMAND_PHONEBOOK_READ_RECORD";
                break;
            case MessageType.COMMAND_PHONEBOOK_WRITE_RECORD:
                result = "COMMAND_PHONEBOOK_WRITE_RECORD";
                break;

            case MessageType.RESPONSE_CALL_CALLBACK:
                result = "RESPONSE_CALL_CALLBACK";
                break;
            case MessageType.RESPONSE_CALL_RETURN:
                result = "RESPONSE_CALL_RETURN";
                break;

            case MessageType.RESPONSE_STATE_CALLBACK:
                result = "RESPONSE_STATE_CALLBACK";
                break;

            case MessageType.RESPONSE_MISC_TEST_ALIVE:
                result = "RESPONSE_MISC_TEST_ALIVE";
                break;
            case MessageType.RESPONSE_MISC_GET_RADIO_FIRMWARE_VERSION:
                result = "RESPONSE_MISC_GET_RADIO_FIRMWARE_VERSION";
                break;
            case MessageType.RESPONSE_MISC_GET_CHARGER_STATUS:
                result = "RESPONSE_MISC_GET_CHARGER_STATUS";
                break;
            case MessageType.RESPONSE_MISC_SET_CHARGE:
                result = "RESPONSE_MISC_SET_CHARGE";
                break;
            case MessageType.RESPONSE_MISC_SET_DATE:
                result = "RESPONSE_MISC_SET_DATE";
                break;
            case MessageType.RESPONSE_MISC_GET_IMEI:
                result = "RESPONSE_MISC_GET_IMEI";
                break;

            case MessageType.RESPONSE_SIM_CALLBACK:
                result = "RESPONSE_SIM_CALLBACK";
                break;

            case MessageType.RESPONSE_PHONEBOOK_RETURN:
                result = "RESPONSE_PHONEBOOK_RETURN";
                break;

            case MessageType.UNSOLICITED_RESPONSE_STATE_OPRT_MODE:
                result = "UNSOLICITED_RESPONSE_STATE_OPRT_MODE";
                break;
            case MessageType.UNSOLICITED_RESPONSE_STATE_TEST_CONTROL_TYPE:
                result = "UNSOLICITED_RESPONSE_STATE_TEST_CONTROL_TYPE";
                break;
            case MessageType.UNSOLICITED_RESPONSE_STATE_SYS_SEL_PREF:
                result = "UNSOLICITED_RESPONSE_STATE_SYS_SEL_PREF";
                break;
            case MessageType.UNSOLICITED_RESPONSE_STATE_ANSWER_VOICE:
                result = "UNSOLICITED_RESPONSE_STATE_ANSWER_VOICE";
                break;
            case MessageType.UNSOLICITED_RESPONSE_STATE_NAM_SEL:
                result = "UNSOLICITED_RESPONSE_STATE_NAM_SEL";
                break;
            case MessageType.UNSOLICITED_RESPONSE_STATE_CURR_NAM:
                result = "UNSOLICITED_RESPONSE_STATE_CURR_NAM";
                break;
            case MessageType.UNSOLICITED_RESPONSE_STATE_IN_USE_STATE:
                result = "UNSOLICITED_RESPONSE_STATE_IN_USE_STATE";
                break;
            case MessageType.UNSOLICITED_RESPONSE_STATE_CDMA_LOCK_MODE:
                result = "UNSOLICITED_RESPONSE_STATE_CDMA_LOCK_MODE";
                break;
            case MessageType.UNSOLICITED_RESPONSE_STATE_UZ_CHANGED:
                result = "UNSOLICITED_RESPONSE_STATE_UZ_CHANGED";
                break;
            case MessageType.UNSOLICITED_RESPONSE_STATE_MAINTREQ:
                result = "UNSOLICITED_RESPONSE_STATE_MAINTREQ";
                break;
            case MessageType.UNSOLICITED_RESPONSE_STATE_STANDBY_SLEEP:
                result = "UNSOLICITED_RESPONSE_STATE_STANDBY_SLEEP";
                break;
            case MessageType.UNSOLICITED_RESPONSE_STATE_STANDBY_WAKE:
                result = "UNSOLICITED_RESPONSE_STATE_STANDBY_WAKE";
                break;
            case MessageType.UNSOLICITED_RESPONSE_STATE_INFO:
                result = "UNSOLICITED_RESPONSE_STATE_INFO";
                break;
            case MessageType.UNSOLICITED_RESPONSE_STATE_PACKET_STATE:
                result = "UNSOLICITED_RESPONSE_STATE_PACKET_STATE";
                break;
            case MessageType.UNSOLICITED_RESPONSE_STATE_INFO_AVAIL:
                result = "UNSOLICITED_RESPONSE_STATE_INFO_AVAIL";
                break;
            case MessageType.UNSOLICITED_RESPONSE_STATE_SUBSCRIPTION_AVAILABLE:
                result = "UNSOLICITED_RESPONSE_STATE_SUBSCRIPTION_AVAILABLE";
                break;
            case MessageType.UNSOLICITED_RESPONSE_STATE_SUBSCRIPTION_NOT_AVAILABLE:
                result = "UNSOLICITED_RESPONSE_STATE_SUBSCRIPTION_NOT_AVAILABLE";
                break;
            case MessageType.UNSOLICITED_RESPONSE_STATE_SUBSCRIPTION_CHANGED:
                result = "UNSOLICITED_RESPONSE_STATE_SUBSCRIPTION_CHANGED";
                break;
            case MessageType.UNSOLICITED_RESPONSE_STATE_AVAILABLE_NETWORKS_CONF:
                result = "UNSOLICITED_RESPONSE_STATE_AVAILABLE_NETWORKS_CONF";
                break;
            case MessageType.UNSOLICITED_RESPONSE_STATE_PREFERRED_NETWORKS_CONF:
                result = "UNSOLICITED_RESPONSE_STATE_PREFERRED_NETWORKS_CONF";
                break;
            case MessageType.UNSOLICITED_RESPONSE_STATE_FUNDS_LOW:
                result = "UNSOLICITED_RESPONSE_STATE_FUNDS_LOW";
                break;
            case MessageType.UNSOLICITED_RESPONSE_STATE_WAKEUP_FROM_STANDBY:
                result = "UNSOLICITED_RESPONSE_STATE_WAKEUP_FROM_STANDBY";
                break;
            case MessageType.UNSOLICITED_RESPONSE_STATE_NVRUIM_CONFIG_CHANGED:
                result = "UNSOLICITED_RESPONSE_STATE_NVRUIM_CONFIG_CHANGED";
                break;
            case MessageType.UNSOLICITED_RESPONSE_STATE_PREFERRED_NETWORKS_SET:
                result = "UNSOLICITED_RESPONSE_STATE_PREFERRED_NETWORKS_SET";
                break;
            case MessageType.UNSOLICITED_RESPONSE_STATE_DDTM_PREF:
                result = "UNSOLICITED_RESPONSE_STATE_DDTM_PREF";
                break;
            case MessageType.UNSOLICITED_RESPONSE_STATE_PS_ATTACH_FAILED:
                result = "UNSOLICITED_RESPONSE_STATE_PS_ATTACH_FAILED";
                break;
            case MessageType.UNSOLICITED_RESPONSE_STATE_RESET_ACM_COMPLETED:
                result = "UNSOLICITED_RESPONSE_STATE_RESET_ACM_COMPLETED";
                break;
            case MessageType.UNSOLICITED_RESPONSE_STATE_SET_ACMMAX_COMPLETED:
                result = "UNSOLICITED_RESPONSE_STATE_SET_ACMMAX_COMPLETED";
                break;
            case MessageType.UNSOLICITED_RESPONSE_STATE_CDMA_CAPABILITY_UPDATED:
                result = "UNSOLICITED_RESPONSE_STATE_CDMA_CAPABILITY_UPDATED";
                break;
            case MessageType.UNSOLICITED_RESPONSE_STATE_LINE_SWITCHING:
                result = "UNSOLICITED_RESPONSE_STATE_LINE_SWITCHING";
                break;
            case MessageType.UNSOLICITED_RESPONSE_STATE_SELECTED_LINE:
                result = "UNSOLICITED_RESPONSE_STATE_SELECTED_LINE";
                break;
            case MessageType.UNSOLICITED_RESPONSE_STATE_SECONDARY_MSM:
                result = "UNSOLICITED_RESPONSE_STATE_SECONDARY_MSM";
                break;
            case MessageType.UNSOLICITED_RESPONSE_STATE_TERMINATE_GET_NETWORKS:
                result = "UNSOLICITED_RESPONSE_STATE_TERMINATE_GET_NETWORKS";
                break;
            case MessageType.UNSOLICITED_RESPONSE_STATE_DDTM_STATUS:
                result = "UNSOLICITED_RESPONSE_STATE_DDTM_STATUS";
                break;
            case MessageType.UNSOLICITED_RESPONSE_STATE_CCBS_STORE_INFO_CHANGED:
                result = "UNSOLICITED_RESPONSE_STATE_CCBS_STORE_INFO_CHANGED";
                break;
            case MessageType.UNSOLICITED_RESPONSE_STATE_EVENT_UNFORCE_ORIG_COMPLETE:
                result = "UNSOLICITED_RESPONSE_STATE_EVENT_UNFORCE_ORIG_COMPLETE";
                break;
            case MessageType.UNSOLICITED_RESPONSE_STATE_SEND_MANUAL_NET_SELECTN:
                result = "UNSOLICITED_RESPONSE_STATE_SEND_MANUAL_NET_SELECTN";
                break;

            case MessageType.UNSOLICITED_RESPONSE_MISC_RADIO_RESET_IND:
                result = "UNSOLICITED_RESPONSE_MISC_RADIO_RESET_IND";
                break;
            case MessageType.UNSOLICITED_RESPONSE_MISC_CHARGER_STATUS:
                result = "UNSOLICITED_RESPONSE_MISC_CHARGER_STATUS";
                break;


            case MessageType.UNSOLICITED_RESPONSE_SIM_SIM_INSERTED:
                result = "UNSOLICITED_RESPONSE_SIM_SIM_INSERTED";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_SIM_REMOVED:
                result = "UNSOLICITED_RESPONSE_SIM_SIM_REMOVED";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_DRIVER_ERROR:
                result = "UNSOLICITED_RESPONSE_SIM_DRIVER_ERROR";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_CARD_ERROR:
                result = "UNSOLICITED_RESPONSE_SIM_CARD_ERROR";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_MEMORY_WARNING:
                result = "UNSOLICITED_RESPONSE_SIM_MEMORY_WARNING";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_NO_SIM_EVENT:
                result = "UNSOLICITED_RESPONSE_SIM_NO_SIM_EVENT";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_NO_SIM:
                result = "UNSOLICITED_RESPONSE_SIM_NO_SIM";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_SIM_INIT_COMPLETED:
                result = "UNSOLICITED_RESPONSE_SIM_SIM_INIT_COMPLETED";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_SIM_INIT_COMPLETED_NO_PROV:
                result = "UNSOLICITED_RESPONSE_SIM_SIM_INIT_COMPLETED_NO_PROV";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_PIN1_VERIFIED:
                result = "UNSOLICITED_RESPONSE_SIM_PIN1_VERIFIED";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_PIN1_BLOCKED:
                result = "UNSOLICITED_RESPONSE_SIM_PIN1_BLOCKED";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_PIN1_UNBLOCKED:
                result = "UNSOLICITED_RESPONSE_SIM_PIN1_UNBLOCKED";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_PIN1_ENABLED:
                result = "UNSOLICITED_RESPONSE_SIM_PIN1_ENABLED";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_PIN1_DISABLED:
                result = "UNSOLICITED_RESPONSE_SIM_PIN1_DISABLED";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_PIN1_CHANGED:
                result = "UNSOLICITED_RESPONSE_SIM_PIN1_CHANGED";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_PIN1_PERM_BLOCKED:
                result = "UNSOLICITED_RESPONSE_SIM_PIN1_PERM_BLOCKED";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_PIN2_VERIFIED:
                result = "UNSOLICITED_RESPONSE_SIM_PIN2_VERIFIED";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_PIN2_BLOCKED:
                result = "UNSOLICITED_RESPONSE_SIM_PIN2_BLOCKED";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_PIN2_UNBLOCKED:
                result = "UNSOLICITED_RESPONSE_SIM_PIN2_UNBLOCKED";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_PIN2_ENABLED:
                result = "UNSOLICITED_RESPONSE_SIM_PIN2_ENABLED";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_PIN2_DISABLED:
                result = "UNSOLICITED_RESPONSE_SIM_PIN2_DISABLED";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_PIN2_CHANGED:
                result = "UNSOLICITED_RESPONSE_SIM_PIN2_CHANGED";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_PIN2_PERM_BLOCKED:
                result = "UNSOLICITED_RESPONSE_SIM_PIN2_PERM_BLOCKED";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_NO_EVENT:
                result = "UNSOLICITED_RESPONSE_SIM_NO_EVENT";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_OK_FOR_TERMINAL_PROFILE_DL:
                result = "UNSOLICITED_RESPONSE_SIM_OK_FOR_TERMINAL_PROFILE_DL";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_NOT_OK_FOR_TERMINAL_PROFILE_DL:
                result = "UNSOLICITED_RESPONSE_SIM_NOT_OK_FOR_TERMINAL_PROFILE_DL";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_REFRESH_SIM_RESET:
                result = "UNSOLICITED_RESPONSE_SIM_REFRESH_SIM_RESET";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_REFRESH_SIM_INIT:
                result = "UNSOLICITED_RESPONSE_SIM_REFRESH_SIM_INIT";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_FDN_ENABLE:
                result = "UNSOLICITED_RESPONSE_SIM_FDN_ENABLE";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_FDN_DISABLE:
                result = "UNSOLICITED_RESPONSE_SIM_FDN_DISABLE";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_SIM_INSERTED_2:
                result = "UNSOLICITED_RESPONSE_SIM_SIM_INSERTED_2";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_SIM_REMOVED_2:
                result = "UNSOLICITED_RESPONSE_SIM_SIM_REMOVED_2";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_CARD_ERROR_2:
                result = "UNSOLICITED_RESPONSE_SIM_CARD_ERROR_2";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_MEMORY_WARNING_2:
                result = "UNSOLICITED_RESPONSE_SIM_MEMORY_WARNING_2";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_NO_SIM_EVENT_2:
                result = "UNSOLICITED_RESPONSE_SIM_NO_SIM_EVENT_2";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_SIM_INIT_COMPLETED_2:
                result = "UNSOLICITED_RESPONSE_SIM_SIM_INIT_COMPLETED_2";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_SIM_INIT_COMPLETED_NO_PROV_2:
                result = "UNSOLICITED_RESPONSE_SIM_SIM_INIT_COMPLETED_NO_PROV_2";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_PIN1_VERIFIED_2:
                result = "UNSOLICITED_RESPONSE_SIM_PIN1_VERIFIED_2";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_PIN1_BLOCKED_2:
                result = "UNSOLICITED_RESPONSE_SIM_PIN1_BLOCKED_2";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_PIN1_UNBLOCKED_2:
                result = "UNSOLICITED_RESPONSE_SIM_PIN1_UNBLOCKED_2";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_PIN1_ENABLED_2:
                result = "UNSOLICITED_RESPONSE_SIM_PIN1_ENABLED_2";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_PIN1_DISABLED_2:
                result = "UNSOLICITED_RESPONSE_SIM_PIN1_DISABLED_2";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_PIN1_CHANGED_2:
                result = "UNSOLICITED_RESPONSE_SIM_PIN1_CHANGED_2";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_PIN1_PERM_BLOCKED_2:
                result = "UNSOLICITED_RESPONSE_SIM_PIN1_PERM_BLOCKED_2";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_PIN2_VERIFIED_2:
                result = "UNSOLICITED_RESPONSE_SIM_PIN2_VERIFIED_2";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_PIN2_BLOCKED_2:
                result = "UNSOLICITED_RESPONSE_SIM_PIN2_BLOCKED_2";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_PIN2_UNBLOCKED_2:
                result = "UNSOLICITED_RESPONSE_SIM_PIN2_UNBLOCKED_2";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_PIN2_ENABLED_2:
                result = "UNSOLICITED_RESPONSE_SIM_PIN2_ENABLED_2";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_PIN2_DISABLED_2:
                result = "UNSOLICITED_RESPONSE_SIM_PIN2_DISABLED_2";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_PIN2_CHANGED_2:
                result = "UNSOLICITED_RESPONSE_SIM_PIN2_CHANGED_2";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_PIN2_PERM_BLOCKED_2:
                result = "UNSOLICITED_RESPONSE_SIM_PIN2_PERM_BLOCKED_2";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_REFRESH_SIM_RESET_2:
                result = "UNSOLICITED_RESPONSE_SIM_REFRESH_SIM_RESET_2";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_REFRESH_SIM_INIT_2:
                result = "UNSOLICITED_RESPONSE_SIM_REFRESH_SIM_INIT_2";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_FDN_ENABLE_2:
                result = "UNSOLICITED_RESPONSE_SIM_FDN_ENABLE_2";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_FDN_DISABLE_2:
                result = "UNSOLICITED_RESPONSE_SIM_FDN_DISABLE_2";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_OK_FOR_TERMINAL_PROFILE_DL_2:
                result = "UNSOLICITED_RESPONSE_SIM_OK_FOR_TERMINAL_PROFILE_DL_2";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_NOT_OK_FOR_TERMINAL_PROFILE_DL_2:
                result = "UNSOLICITED_RESPONSE_SIM_NOT_OK_FOR_TERMINAL_PROFILE_DL_2";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_REFRESH_SIM_INIT_FCN:
                result = "UNSOLICITED_RESPONSE_SIM_REFRESH_SIM_INIT_FCN";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_REFRESH_SIM_INIT_FCN_2:
                result = "UNSOLICITED_RESPONSE_SIM_REFRESH_SIM_INIT_FCN_2";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_REFRESH_FCN:
                result = "UNSOLICITED_RESPONSE_SIM_REFRESH_FCN";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_REFRESH_FCN_2:
                result = "UNSOLICITED_RESPONSE_SIM_REFRESH_FCN_2";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_REFRESH_FAILED:
                result = "UNSOLICITED_RESPONSE_SIM_REFRESH_FAILED";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_START_SWITCH_SLOT:
                result = "UNSOLICITED_RESPONSE_SIM_START_SWITCH_SLOT";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_FINISH_SWITCH_SLOT:
                result = "UNSOLICITED_RESPONSE_SIM_FINISH_SWITCH_SLOT";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_PERSO_INIT_COMPLETED:
                result = "UNSOLICITED_RESPONSE_SIM_PERSO_INIT_COMPLETED";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_PERSO_EVENT_GEN_PROP1:
                result = "UNSOLICITED_RESPONSE_SIM_PERSO_EVENT_GEN_PROP1";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_SIM_ILLEGAL:
                result = "UNSOLICITED_RESPONSE_SIM_SIM_ILLEGAL";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_SIM_ILLEGAL_2:
                result = "UNSOLICITED_RESPONSE_SIM_SIM_ILLEGAL_2";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_SIM_UHZI_V2_COMPLETE:
                result = "UNSOLICITED_RESPONSE_SIM_SIM_UHZI_V2_COMPLETE";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_SIM_UHZI_V1_COMPLETE:
                result = "UNSOLICITED_RESPONSE_SIM_SIM_UHZI_V1_COMPLETE";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_PERSO_EVENT_GEN_PROP2:
                result = "UNSOLICITED_RESPONSE_SIM_PERSO_EVENT_GEN_PROP2";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_INTERNAL_SIM_RESET:
                result = "UNSOLICITED_RESPONSE_SIM_INTERNAL_SIM_RESET";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_CARD_ERR_POLL_ERROR:
                result = "UNSOLICITED_RESPONSE_SIM_CARD_ERR_POLL_ERROR";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_CARD_ERR_NO_ATR_RECEIVED_WITH_MAX_VOLTAGE:
                result = "UNSOLICITED_RESPONSE_SIM_CARD_ERR_NO_ATR_RECEIVED_WITH_MAX_VOLTAGE";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_CARD_ERR_NO_ATR_RECEIVED_AFTER_INT_RESET:
                result = "UNSOLICITED_RESPONSE_SIM_CARD_ERR_NO_ATR_RECEIVED_AFTER_INT_RESET";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_CARD_ERR_CORRUPT_ATR_RCVD_MAX_TIMES:
                result = "UNSOLICITED_RESPONSE_SIM_CARD_ERR_CORRUPT_ATR_RCVD_MAX_TIMES";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_CARD_ERR_PPS_TIMED_OUT_MAX_TIMES:
                result = "UNSOLICITED_RESPONSE_SIM_CARD_ERR_PPS_TIMED_OUT_MAX_TIMES";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_CARD_ERR_VOLTAGE_MISMATCH:
                result = "UNSOLICITED_RESPONSE_SIM_CARD_ERR_VOLTAGE_MISMATCH";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_CARD_ERR_INT_CMD_TIMED_OUT_AFTER_PPS:
                result = "UNSOLICITED_RESPONSE_SIM_CARD_ERR_INT_CMD_TIMED_OUT_AFTER_PPS";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_CARD_ERR_INT_CMD_ERR_EXCEED_MAX_ATTEMPTS:
                result = "UNSOLICITED_RESPONSE_SIM_CARD_ERR_INT_CMD_ERR_EXCEED_MAX_ATTEMPTS";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_CARD_ERR_MAXED_PARITY_ERROR:
                result = "UNSOLICITED_RESPONSE_SIM_CARD_ERR_MAXED_PARITY_ERROR";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_CARD_ERR_MAXED_RX_BREAK_ERROR:
                result = "UNSOLICITED_RESPONSE_SIM_CARD_ERR_MAXED_RX_BREAK_ERROR";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_CARD_ERR_MAXED_OVERRUN_ERROR:
                result = "UNSOLICITED_RESPONSE_SIM_CARD_ERR_MAXED_OVERRUN_ERROR";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_CARD_ERR_TRANSACTION_TIMER_EXPIRED:
                result = "UNSOLICITED_RESPONSE_SIM_CARD_ERR_TRANSACTION_TIMER_EXPIRED";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_CARD_ERR_POWER_DOWN_CMD_NOTIFICATION:
                result = "UNSOLICITED_RESPONSE_SIM_CARD_ERR_POWER_DOWN_CMD_NOTIFICATION";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_CARD_ERR_INT_CMD_ERR_IN_PASSIVE_MODE:
                result = "UNSOLICITED_RESPONSE_SIM_CARD_ERR_INT_CMD_ERR_IN_PASSIVE_MODE";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_CARD_ERR_CMD_TIMED_OUT_IN_PASSIVE_MODE:
                result = "UNSOLICITED_RESPONSE_SIM_CARD_ERR_CMD_TIMED_OUT_IN_PASSIVE_MODE";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_CARD_ERR_MAX_PARITY_IN_PASSIVE:
                result = "UNSOLICITED_RESPONSE_SIM_CARD_ERR_MAX_PARITY_IN_PASSIVE";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_CARD_ERR_MAX_RXBRK_IN_PASSIVE:
                result = "UNSOLICITED_RESPONSE_SIM_CARD_ERR_MAX_RXBRK_IN_PASSIVE";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_CARD_ERR_MAX_OVERRUN_IN_PASSIVE:
                result = "UNSOLICITED_RESPONSE_SIM_CARD_ERR_MAX_OVERRUN_IN_PASSIVE";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_CARD_ERR_POLL_ERROR_2:
                result = "UNSOLICITED_RESPONSE_SIM_CARD_ERR_POLL_ERROR_2";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_CARD_ERR_NO_ATR_RECEIVED_WITH_MAX_VOLTAGE_2:
                result = "UNSOLICITED_RESPONSE_SIM_CARD_ERR_NO_ATR_RECEIVED_WITH_MAX_VOLTAGE_2";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_CARD_ERR_NO_ATR_RECEIVED_AFTER_INT_RESET_2:
                result = "UNSOLICITED_RESPONSE_SIM_CARD_ERR_NO_ATR_RECEIVED_AFTER_INT_RESET_2";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_CARD_ERR_CORRUPT_ATR_RCVD_MAX_TIMES_2:
                result = "UNSOLICITED_RESPONSE_SIM_CARD_ERR_CORRUPT_ATR_RCVD_MAX_TIMES_2";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_CARD_ERR_PPS_TIMED_OUT_MAX_TIMES_2:
                result = "UNSOLICITED_RESPONSE_SIM_CARD_ERR_PPS_TIMED_OUT_MAX_TIMES_2";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_CARD_ERR_VOLTAGE_MISMATCH_2:
                result = "UNSOLICITED_RESPONSE_SIM_CARD_ERR_VOLTAGE_MISMATCH_2";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_CARD_ERR_INT_CMD_TIMED_OUT_AFTER_PPS_2:
                result = "UNSOLICITED_RESPONSE_SIM_CARD_ERR_INT_CMD_TIMED_OUT_AFTER_PPS_2";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_CARD_ERR_INT_CMD_ERR_EXCEED_MAX_ATTEMPTS_2:
                result = "UNSOLICITED_RESPONSE_SIM_CARD_ERR_INT_CMD_ERR_EXCEED_MAX_ATTEMPTS_2";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_CARD_ERR_MAXED_PARITY_ERROR_2:
                result = "UNSOLICITED_RESPONSE_SIM_CARD_ERR_MAXED_PARITY_ERROR_2";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_CARD_ERR_MAXED_RX_BREAK_ERROR_2:
                result = "UNSOLICITED_RESPONSE_SIM_CARD_ERR_MAXED_RX_BREAK_ERROR_2";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_CARD_ERR_MAXED_OVERRUN_ERROR_2:
                result = "UNSOLICITED_RESPONSE_SIM_CARD_ERR_MAXED_OVERRUN_ERROR_2";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_CARD_ERR_TRANSACTION_TIMER_EXPIRED_2:
                result = "UNSOLICITED_RESPONSE_SIM_CARD_ERR_TRANSACTION_TIMER_EXPIRED_2";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_CARD_ERR_POWER_DOWN_CMD_NOTIFICATION_2:
                result = "UNSOLICITED_RESPONSE_SIM_CARD_ERR_POWER_DOWN_CMD_NOTIFICATION_2";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_CARD_ERR_INT_CMD_ERR_IN_PASSIVE_MODE_2:
                result = "UNSOLICITED_RESPONSE_SIM_CARD_ERR_INT_CMD_ERR_IN_PASSIVE_MODE_2";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_CARD_ERR_CMD_TIMED_OUT_IN_PASSIVE_MODE_2:
                result = "UNSOLICITED_RESPONSE_SIM_CARD_ERR_CMD_TIMED_OUT_IN_PASSIVE_MODE_2";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_CARD_ERR_MAX_PARITY_IN_PASSIVE_2:
                result = "UNSOLICITED_RESPONSE_SIM_CARD_ERR_MAX_PARITY_IN_PASSIVE_2";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_CARD_ERR_MAX_RXBRK_IN_PASSIVE_2:
                result = "UNSOLICITED_RESPONSE_SIM_CARD_ERR_MAX_RXBRK_IN_PASSIVE_2";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_CARD_ERR_MAX_OVERRUN_IN_PASSIVE_2:
                result = "UNSOLICITED_RESPONSE_SIM_CARD_ERR_MAX_OVERRUN_IN_PASSIVE_2";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_REFRESH_APP_RESET:
                result = "UNSOLICITED_RESPONSE_SIM_REFRESH_APP_RESET";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_REFRESH_3G_SESSION_RESET:
                result = "UNSOLICITED_RESPONSE_SIM_REFRESH_3G_SESSION_RESET";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_REFRESH_APP_RESET_2:
                result = "UNSOLICITED_RESPONSE_SIM_REFRESH_APP_RESET_2";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_REFRESH_3G_SESSION_RESET_2:
                result = "UNSOLICITED_RESPONSE_SIM_REFRESH_3G_SESSION_RESET_2";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_APP_SELECTED:
                result = "UNSOLICITED_RESPONSE_SIM_APP_SELECTED";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_APP_SELECTED_2:
                result = "UNSOLICITED_RESPONSE_SIM_APP_SELECTED_2";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_PERSO_NW_FAILURE:
                result = "UNSOLICITED_RESPONSE_SIM_PERSO_NW_FAILURE";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_PERSO_NS_FAILURE:
                result = "UNSOLICITED_RESPONSE_SIM_PERSO_NS_FAILURE";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_PERSO_SP_FAILURE:
                result = "UNSOLICITED_RESPONSE_SIM_PERSO_SP_FAILURE";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_PERSO_CP_FAILURE:
                result = "UNSOLICITED_RESPONSE_SIM_PERSO_CP_FAILURE";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_PERSO_SIM_FAILURE:
                result = "UNSOLICITED_RESPONSE_SIM_PERSO_SIM_FAILURE";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_PERSO_NW_DEACTIVATED:
                result = "UNSOLICITED_RESPONSE_SIM_PERSO_NW_DEACTIVATED";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_PERSO_NS_DEACTIVATED:
                result = "UNSOLICITED_RESPONSE_SIM_PERSO_NS_DEACTIVATED";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_PERSO_SP_DEACTIVATED:
                result = "UNSOLICITED_RESPONSE_SIM_PERSO_SP_DEACTIVATED";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_PERSO_CP_DEACTIVATED:
                result = "UNSOLICITED_RESPONSE_SIM_PERSO_CP_DEACTIVATED";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_PERSO_SIM_DEACTIVATED:
                result = "UNSOLICITED_RESPONSE_SIM_PERSO_SIM_DEACTIVATED";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_PERSO_NCK_BLOCKED:
                result = "UNSOLICITED_RESPONSE_SIM_PERSO_NCK_BLOCKED";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_PERSO_NSK_BLOCKED:
                result = "UNSOLICITED_RESPONSE_SIM_PERSO_NSK_BLOCKED";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_PERSO_SPK_BLOCKED:
                result = "UNSOLICITED_RESPONSE_SIM_PERSO_SPK_BLOCKED";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_PERSO_CCK_BLOCKED:
                result = "UNSOLICITED_RESPONSE_SIM_PERSO_CCK_BLOCKED";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_PERSO_PPK_BLOCKED:
                result = "UNSOLICITED_RESPONSE_SIM_PERSO_PPK_BLOCKED";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_PERSO_NCK_UNBLOCKED:
                result = "UNSOLICITED_RESPONSE_SIM_PERSO_NCK_UNBLOCKED";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_PERSO_NSK_UNBLOCKED:
                result = "UNSOLICITED_RESPONSE_SIM_PERSO_NSK_UNBLOCKED";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_PERSO_SPK_UNBLOCKED:
                result = "UNSOLICITED_RESPONSE_SIM_PERSO_SPK_UNBLOCKED";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_PERSO_CCK_UNBLOCKED:
                result = "UNSOLICITED_RESPONSE_SIM_PERSO_CCK_UNBLOCKED";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_PERSO_PPK_UNBLOCKED:
                result = "UNSOLICITED_RESPONSE_SIM_PERSO_PPK_UNBLOCKED";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_PERSO_SANITY_ERROR:
                result = "UNSOLICITED_RESPONSE_SIM_PERSO_SANITY_ERROR";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_PERSO_GEN_PROP1:
                result = "UNSOLICITED_RESPONSE_SIM_PERSO_GEN_PROP1";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_PERSO_GEN_PROP2:
                result = "UNSOLICITED_RESPONSE_SIM_PERSO_GEN_PROP2";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_PERSO_EVT_INIT_COMPLETED:
                result = "UNSOLICITED_RESPONSE_SIM_PERSO_EVT_INIT_COMPLETED";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_PLMN_SEL_MENU_ENABLE:
                result = "UNSOLICITED_RESPONSE_SIM_PLMN_SEL_MENU_ENABLE";
                break;
            case MessageType.UNSOLICITED_RESPONSE_SIM_PLMN_SEL_MENU_DISABLE:
                result = "UNSOLICITED_RESPONSE_SIM_PLMN_SEL_MENU_D";
                break;

            case MessageType.UNSOLICITED_RESPONSE_PHONEBOOK_PHONEBOOK_READY:
                result = "UNSOLICITED_RESPONSE_PHONEBOOK_PHONEBOOK_READY";
                break;
        }

        return result;
    }
}

