/* 
 * (c) 2010 by Simon Busch <morphis@gravedo.de>
 * All Rights Reserved
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 */
#ifndef STRUCTURES_H_
#define STRUCTURES_H_

/* All structures in this file are autogenerated by generate_structs.py */

struct call_status_event
{
	uint8_t unknown0;
	uint8_t call_id;
	uint8_t host_call_id;
	uint8_t unknown1;
	uint8_t caller_id[15];
	uint8_t unknown2[45];
	uint8_t caller_id_len;
	uint8_t unknown3[526];
	uint8_t cause_value0;
	uint8_t unknown4[4];
	uint8_t cause_value1;
	uint8_t unknown5[28];
	uint8_t cause_value2;
	uint8_t reject_type;
	uint8_t reject_value;
	uint8_t unknown6[480];
} __attribute__ ((packed));


struct cm_call_resp
{
	uint8_t unknown0;
	uint8_t ref_id;
	uint8_t unknown1[9];
} __attribute__ ((packed));


struct answer_call_msg
{
	uint8_t unknown0;
	uint8_t ref_id;
	uint8_t unknown1[3];
	uint8_t host_id;
	uint8_t call_nr;
	uint8_t unknown2[2];
} __attribute__ ((packed));


struct end_call_msg
{
	uint8_t unknown0;
	uint8_t ref_id;
	uint8_t unknown1[3];
	uint8_t host_id;
	uint8_t call_nr;
	uint8_t unknown2[55];
} __attribute__ ((packed));


struct get_sim_capabilities_resp
{
	uint8_t unknown0[1935];
} __attribute__ ((packed));


struct verify_pin_msg
{
	uint8_t unknown0;
	uint8_t pin_type;
	uint8_t unknown1[4];
	uint8_t pin[8];
	uint8_t unknown2;
} __attribute__ ((packed));


struct cm_ss_event
{
	uint8_t change_field[8];
	uint8_t new_value;
	uint8_t unknown0[7];
	uint8_t plmn[3];
	uint8_t unknown1[3];
	uint8_t operator_name_len;
	uint8_t operator_name[80];
	uint8_t unknown2[23];
	uint8_t rssi;
	uint8_t unknown3;
	uint8_t ecio;
	uint8_t unknown4[549];
} __attribute__ ((packed));


struct charger_status_event
{
	uint8_t unknown0[6];
	uint16_t voltage;
	uint8_t unknown1[7];
} __attribute__ ((packed));


struct radio_reset_ind_event
{
} __attribute__ ((packed));


struct operator_mode_event
{
} __attribute__ ((packed));


struct power_state_event
{
	uint8_t unknown0[5];
	uint8_t power_state;
	uint8_t unknown1[7];
} __attribute__ ((packed));


struct test_alive_event
{
} __attribute__ ((packed));


struct get_firmware_info_resp
{
	uint8_t unknown0[5];
	uint8_t hci_version;
	uint8_t unknown1[3];
	uint8_t firmware_version[13];
	uint8_t unknown2[122];
} __attribute__ ((packed));


struct get_imei_resp
{
	uint8_t unknown0[5];
	uint8_t imei[17];
} __attribute__ ((packed));


struct get_charger_status_resp
{
	uint8_t unknown0;
	uint8_t ref_id;
	uint8_t unknown1[4];
	uint16_t voltage;
	uint8_t unknown2[7];
} __attribute__ ((packed));


struct charge_usb_resp
{
	uint8_t unknown0;
	uint8_t ref_id;
	uint8_t unknown1[4];
	uint16_t voltage;
	uint8_t unknown2[2];
} __attribute__ ((packed));


struct get_imei_msg
{
	uint8_t unknown0[5];
} __attribute__ ((packed));


struct change_operation_mode_msg
{
	uint8_t unknown0;
	uint8_t ref_id;
	uint8_t unknown1[3];
	uint8_t operation_mode;
} __attribute__ ((packed));


struct test_alive_msg
{
	uint8_t unknown0[6];
} __attribute__ ((packed));


struct get_firmware_msg
{
	uint8_t unknown0[5];
} __attribute__ ((packed));


struct get_phone_state_info_msg
{
	uint8_t unknown0;
	uint8_t ref_id;
	uint8_t unknown1[3];
} __attribute__ ((packed));


struct set_audio_profile_msg
{
	uint8_t unknown0;
	uint8_t ref_id;
	uint8_t unknown1[9];
} __attribute__ ((packed));


struct get_charger_status_msg
{
	uint8_t unknown0;
	uint8_t ref_id;
	uint8_t unknown1[12];
} __attribute__ ((packed));


struct charge_usb_msg
{
	uint8_t unknown0;
	uint8_t ref_id;
	uint8_t unknown1[4];
	uint16_t voltage;
	uint8_t unknown2[2];
} __attribute__ ((packed));


struct sound_resp
{
	uint8_t unknown0[12];
} __attribute__ ((packed));


struct pdsm_pd_done_event
{
} __attribute__ ((packed));


struct pd_position_data_event
{
} __attribute__ ((packed));


struct pd_parameter_change_event
{
} __attribute__ ((packed));


struct pdsm_lcs_event
{
} __attribute__ ((packed));


struct pdsm_xtra_event
{
} __attribute__ ((packed));


struct pdsm_pd_get_pos_resp
{
} __attribute__ ((packed));


struct pdsm_pd_end_session_resp
{
} __attribute__ ((packed));


struct pa_set_param_resp
{
} __attribute__ ((packed));


struct lcs_agent_client_rsp_resp
{
} __attribute__ ((packed));


struct xtra_set_data_resp
{
} __attribute__ ((packed));


struct get_location_priv_pref_msg
{
	uint8_t unknown0[13];
} __attribute__ ((packed));

#endif

