/* 
 * (c) 2010 by Simon Busch <morphis@gravedo.de>
 * All Rights Reserved
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 */

#include "internal.h"

extern void *talloc_msmc_ctx;

unsigned int network_plmn_to_value(const uint8_t *plmn)
{
    unsigned int value = 0;
    value = (plmn[0] & 0xf) * 10000;
    value += ((plmn[0] & 0xf0) >> 4) * 1000;
    value += (plmn[1] & 0xf) * 100;
    value += (plmn[2] & 0xf) * 10;
    value += ((plmn[2] & 0xf0) >> 4);
    return value;
}

/*
 * Common methods for pin_status_msg types
 */

void _message_pin_status_set_pin(struct msmcomm_message *msg, const char *pin)
{
    int len = strlen(pin);
    unsigned int bytes = 0;
    
    /* A valid pin should be 4 or 8 bytes long */
    if (len >= 4)
    {
        bytes = 4; 
    }
    else if (len >= 8)
    {
        bytes = 8;
    }
    
    memcpy(MESSAGE_CAST(msg, struct pin_status_msg)->pin, pin, bytes);
}

void _message_pin_status_set_pin_type(struct msmcomm_message *msg, msmcomm_sim_pin_type_t pin_type)
{
    unsigned int type = 0x0;
    switch (pin_type) 
    {
        case MSMCOMM_SIM_PIN_1:
            type = 0x0;
            break;
        case MSMCOMM_SIM_PIN_2:
            type = 0x1;
            break;
    }
    MESSAGE_CAST(msg, struct pin_status_msg)->pin_type = type;
}

/*
 * Various to-string methods
 */

char *msmcomm_message_type_to_string(msmcomm_message_type_t type)
{
	switch (type)
	{
		case MSMCOMM_MESSAGE_TYPE_INVALID:
			return "INVALID";
		case MSMCOMM_MESSAGE_TYPE_NOT_USED:
			return "NOT_USED";
		case MSMCOMM_MESSAGE_TYPE_COMMAND_CHANGE_OPERATION_MODE:
			return "COMMAND_CHANGE_OPERATION_MODE";
		case MSMCOMM_MESSAGE_TYPE_COMMAND_GET_IMEI:
			return "COMMAND_GET_IMEI";
		case MSMCOMM_MESSAGE_TYPE_COMMAND_GET_FIRMWARE_INFO:
			return "COMMAND_GET_FIRMWARE_INFO";
		case MSMCOMM_MESSAGE_TYPE_COMMAND_TEST_ALIVE:
			return "COMMAND_TEST_ALIVE";
		case MSMCOMM_MESSAGE_TYPE_COMMAND_GET_PHONE_STATE_INFO:
			return "COMMAND_GET_PHONE_STATE_INFO";
		case MSMCOMM_MESSAGE_TYPE_COMMAND_VERIFY_PIN:
			return "COMMAND_VERIFY_PIN";
		case MSMCOMM_MESSAGE_TYPE_COMMAND_GET_VOICEMAIL_NR:
			return "COMMAND_GET_VOICEMAIL_NR";
		case MSMCOMM_MESSAGE_TYPE_COMMAND_GET_LOCATION_PRIV_PREF:
			return "COMMAND_GET_LOCATION_PRIV_PREF";
		case MSMCOMM_MESSAGE_TYPE_COMMAND_CM_CALL_ANSWER:
			return "COMMAND_CM_CALL_ANSWER";
		case MSMCOMM_MESSAGE_TYPE_COMMAND_SET_AUDIO_PROFILE:
			return "COMMAND_SET_AUDIO_PROFILE";
		case MSMCOMM_MESSAGE_TYPE_COMMAND_CM_CALL_END:
			return "COMMAND_CM_CALL_END";
		case MSMCOMM_MESSAGE_TYPE_COMMAND_GET_CHARGER_STATUS:
			return "COMMAND_GET_CHARGER_STATUS";
		case MSMCOMM_MESSAGE_TYPE_COMMAND_CHARGING:
			return "COMMAND_CHARGING";
		case MSMCOMM_MESSAGE_TYPE_COMMAND_CM_CALL_ORIGINATION:
			return "COMMAND_CM_CALL_ORIGINATION";
		case MSMCOMM_MESSAGE_TYPE_COMMAND_SET_SYSTEM_TIME:
			return "COMMAND_SET_SYSTEM_TIME";
		case MSMCOMM_MESSAGE_TYPE_COMMAND_RSSI_STATUS:
			return "COMMAND_RSSI_STATUS";
		case MSMCOMM_MESSAGE_TYPE_COMMAND_READ_PHONEBOOK:
			return "COMMAND_READ_PHONEBOOK";
		case MSMCOMM_MESSAGE_TYPE_COMMAND_GET_NETWORKLIST:
			return "COMMAND_GET_NETWORKLIST";
		case MSMCOMM_MESSAGE_TYPE_COMMAND_SET_MODE_PREFERENCE:
			return "COMMAND_SET_MODE_PREFERENCE";
		case MSMCOMM_MESSAGE_TYPE_COMMAND_GET_PHONEBOOK_PROPERTIES:
			return "COMMAND_GET_PHONEBOOK_PROPERTIES";
		case MSMCOMM_MESSAGE_TYPE_COMMAND_WRITE_PHONEBOOK:
			return "COMMAND_WRITE_PHONEBOOK";
		case MSMCOMM_MESSAGE_TYPE_COMMAND_DELETE_PHONEBOOK:
			return "COMMAND_DELETE_PHONEBOOK";
		case MSMCOMM_MESSAGE_TYPE_COMMAND_CHANGE_PIN:
			return "COMMAND_CHANGE_PIN";
		case MSMCOMM_MESSAGE_TYPE_COMMAND_ENABLE_PIN:
			return "COMMAND_ENABLE_PI";
		case MSMCOMM_MESSAGE_TYPE_COMMAND_DISABLE_PIN:
			return "COMMAND_DISABLE_PI";
		case MSMCOMM_MESSAGE_TYPE_COMMAND_SIM_INFO:
			return "COMMAND_SIM_INFO";
		case MSMCOMM_MESSAGE_TYPE_COMMAND_GET_AUDIO_MODEM_TUNING_PARAMS:
			return "COMMAND_GET_AUDIO_MODEM_TUNING_PARAMS";
		case MSMCOMM_MESSAGE_TYPE_COMMAND_SMS_ACKNOWLDEGE_INCOMMING_MESSAGE:
			return "COMMAND_SMS_ACKNOWLDEGE_INCOMMING_MESSAGE";
		case MSMCOMM_MESSAGE_TYPE_COMMAND_SMS_GET_SMS_CENTER_NUMBER:
			return "COMMAND_SMS_GET_SMS_CENTER_NUMBER";
		case MSMCOMM_MESSAGE_TYPE_COMMAND_CM_CALL_SUPS:
			return "COMMAND_CM_CALL_SUPS";
		case MSMCOMM_MESSAGE_TYPE_COMMAND_GET_HOME_NETWORK_NAME:
			return "COMMAND_GET_HOME_NETWORK_NAME";
		case MSMCOMM_MESSAGE_TYPE_RESPONSE_TEST_ALIVE:
			return "RESPONSE_TEST_ALIVE";
		case MSMCOMM_MESSAGE_TYPE_RESPONSE_GET_FIRMWARE_INFO:
			return "RESPONSE_GET_FIRMWARE_INFO";
		case MSMCOMM_MESSAGE_TYPE_RESPONSE_GET_IMEI:
			return "RESPONSE_GET_IMEI";
		case MSMCOMM_MESSAGE_TYPE_RESPONSE_PDSM_PD_GET_POS:
			return "RESPONSE_PDSM_PD_GET_POS";
		case MSMCOMM_MESSAGE_TYPE_RESPONSE_PDSM_PD_END_SESSION:
			return "RESPONSE_PDSM_PD_END_SESSION";
		case MSMCOMM_MESSAGE_TYPE_RESPONSE_PA_SET_PARAM:
			return "RESPONSE_PA_SET_PARAM";
		case MSMCOMM_MESSAGE_TYPE_RESPONSE_LCS_AGENT_CLIENT_RSP:
			return "RESPONSE_LCS_AGENT_CLIENT_RSP";
		case MSMCOMM_MESSAGE_TYPE_RESPONSE_XTRA_SET_DATA:
			return "RESPONSE_XTRA_SET_DATA";
		case MSMCOMM_MESSAGE_TYPE_RESPONSE_SIM:
			return "RESPONSE_SIM";
		case MSMCOMM_MESSAGE_TYPE_RESPONSE_GET_VOICEMAIL_NR:
			return "RESPONSE_GET_VOICEMAIL_NR";
		case MSMCOMM_MESSAGE_TYPE_RESPONSE_SOUND:
			return "RESPONSE_SOUND";
		case MSMCOMM_MESSAGE_TYPE_RESPONSE_CM_CALL_RETURN:
			return "RESPONSE_CM_CALL_RETURN";
		case MSMCOMM_MESSAGE_TYPE_RESPONSE_CM_CALL_CALLBACK:
			return "RESPONSE_CM_CALL_CALLBACK";
		case MSMCOMM_MESSAGE_TYPE_RESPONSE_CHARGER_STATUS:
			return "RESPONSE_CHARGER_STATUS";
		case MSMCOMM_MESSAGE_TYPE_RESPONSE_CHARGING:
			return "RESPONSE_CHARGING";
		case MSMCOMM_MESSAGE_TYPE_RESPONSE_CM_PH:
			return "RESPONSE_CM_PH";
		case MSMCOMM_MESSAGE_TYPE_RESPONSE_SET_SYSTEM_TIME:
			return "RESPONSE_SET_SYSTEM_TIME";
		case MSMCOMM_MESSAGE_TYPE_RESPONSE_RSSI_STATUS:
			return "RESPONSE_RSSI_STATUS";
		case MSMCOMM_MESSAGE_TYPE_RESPONSE_PHONEBOOK:
			return "RESPONSE_PHONEBOOK";
		case MSMCOMM_MESSAGE_TYPE_RESPONSE_GET_PHONEBOOK_PROPERTIES:
			return "RESPONSE_GET_PHONEBOOK_PROPERTIES";
		case MSMCOMM_MESSAGE_TYPE_RESPONSE_AUDIO_MODEM_TUNING_PARAMS:
			return "RESPONSE_AUDIO_MODEM_TUNING_PARAMS";
		case MSMCOMM_MESSAGE_TYPE_RESPONSE_SMS_WMS:
			return "RESPONSE_SMS_WMS";
		case MSMCOMM_MESSAGE_TYPE_RESPONSE_GET_HOME_NETWORK_NAME:
			return "RESPONSE_GET_HOME_NETWORK_NAME";
		case MSMCOMM_MESSAGE_TYPE_EVENT_RESET_RADIO_IND:
			return "EVENT_RESET_RADIO_IND";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CHARGER_STATUS:
			return "EVENT_CHARGER_STATUS";
		case MSMCOMM_MESSAGE_TYPE_EVENT_OPERATION_MODE:
			return "EVENT_OPERATION_MODE";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_PH_INFO_AVAILABLE:
			return "EVENT_CM_PH_INFO_AVAILABLE";
		case MSMCOMM_MESSAGE_TYPE_EVENT_NETWORK_STATE_INFO:
			return "EVENT_NETWORK_STATE_INFO";
		case MSMCOMM_MESSAGE_TYPE_EVENT_PD_POSITION_DATA:
			return "EVENT_PD_POSITION_DATA";
		case MSMCOMM_MESSAGE_TYPE_EVENT_PD_PARAMETER_CHANGE:
			return "EVENT_PD_PARAMETER_CHANGE";
		case MSMCOMM_MESSAGE_TYPE_EVENT_PDSM_LCS:
			return "EVENT_PDSM_LCS";

		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_ORIGINATION:
			return "EVENT_CM_CALL_ORIGINATION";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_ANSWER:
			return "EVENT_CM_CALL_ANSWER";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_END_REQ:
			return "EVENT_CM_CALL_END_REQ";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_END:
			return "EVENT_CM_CALL_END";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_SUPS:
			return "EVENT_CM_CALL_SUPS";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_INCOMMING:
			return "EVENT_CM_CALL_INCOMMING";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_CONNECT:
			return "EVENT_CM_CALL_CONNECT";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_SRV_OPT:
			return "EVENT_CM_CALL_SRV_OPT";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_PRIVACY:
			return "EVENT_CM_CALL_PRIVACY";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_PRIVACY_PREF:
			return "EVENT_CM_CALL_PRIVACY_PREF";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_CALLER_ID:
			return "EVENT_CM_CALL_CALLER_ID";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_ABRV_ALTER:
			return "EVENT_CM_CALL_ABRV_ALTER";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_ABRV_REORDER:
			return "EVENT_CM_CALL_ABRV_REORDER";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_ABRV_INTERCEPT:
			return "EVENT_CM_CALL_ABRV_INTERCEPT";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_SIGNAL:
			return "EVENT_CM_CALL_SIGNAL";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_DISPLAY:
			return "EVENT_CM_CALL_DISPLAY";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_CALLED_PARTY:
			return "EVENT_CM_CALL_CALLED_PARTY";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_CONNECTED_NUM:
			return "EVENT_CM_CALL_CONNECTED_NUM";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_INFO:
			return "EVENT_CM_CALL_INFO";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_EXT_DISP:
			return "EVENT_CM_CALL_EXT_DISP";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_NDSS_START:
			return "EVENT_CM_CALL_NDSS_START";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_NDSS_CONNECT:
			return "EVENT_CM_CALL_NDSS_CONNECT";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_EXT_BRST_INTL:
			return "EVENT_CM_CALL_EXT_BRST_INTL";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_NSS_CLIR_REC:
			return "EVENT_CM_CALL_NSS_CLIR_REC";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_NSS_REL_REC:
			return "EVENT_CM_CALL_NSS_REL_REC";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_NSS_AUD_CTRL:
			return "EVENT_CM_CALL_NSS_AUD_CTRL";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_L2ACK_CALL_HOLD:
			return "EVENT_CM_CALL_L2ACK_CALL_HOLD";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_SETUP_IND:
			return "EVENT_CM_CALL_SETUP_IND";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_SETUP_RES:
			return "EVENT_CM_CALL_SETUP_RES";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_CALL_CONF:
			return "EVENT_CM_CALL_CONF";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_PDP_ACTIVATE_IND:
			return "EVENT_CM_CALL_PDP_ACTIVATE_IND";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_PDP_ACTIVATE_RES:
			return "EVENT_CM_CALL_ACITVATE_RES";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_PDP_MODIFY_REQ:
			return "EVENT_CM_CALL_PDP_MODIFY_REQ";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_PDP_MODIFY_IND:
			return "EVENT_CM_CALL_MODIFY_IND";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_PDP_MODIFY_REJ:
			return "EVENT_CM_CALL_MODIFY_REJ";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_PDP_MODIFY_CONF:
			return "EVENT_CM_CALL_MODIFY_CONF";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_RAB_REL_IND:
			return "EVENT_CM_CALL_RAB_REL_IND";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_RAB_REESTAB_IND:
			return "EVENT_CM_CALL_RAB_REESTAB_IND";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_RAB_REESTAB_REQ:
			return "EVENT_CM_CALL_RAB_REESTAB_REQ";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_RAB_REESTAB_CONF:
			return "EVENT_CM_CALL_RAB_REESTAB_CONF";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_RAB_REESTAB_REJ:
			return "EVENT_CM_CALL_RAB_REESTAB_REJ";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_RAB_REESTAB_FAIL:
			return "EVENT_CM_CALL_RAB_REESTAB_FAIL";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_PS_DATA_AVAILABLE:
			return "EVENT_CM_CALL_PS_DATA_AVAILABLE";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_MNG_CALLS_CONF:
			return "EVENT_CM_CALL_CALL_MNG_CALLS_CONF";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_CALL_BARRED:
			return "EVENT_CM_CALL_CALL_BARRED";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_CALL_IS_WAITING:
			return "EVENT_CM_CALL_CALL_IS_WAITING";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_CALL_ON_HOLD:
			return "EVENT_CM_CALL_CALL_ON_HOLD";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_CALL_RETRIEVED:
			return "EVENT_CM_CALL_CALL_RETRIEVED";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_ORIG_FWD_STATUS:
			return "EVENT_CM_CALL_ORIG_FWD_STATUS";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_CALL_FORWARDED:
			return "EVENT_CM_CALL_CALL_FORWARDED";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_CALL_BEING_FORWARDED:
			return "EVENT_CM_CALL_CALL_BEING_FORWARDED";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_INCOM_FWD_CALL:
			return "EVENT_CM_CALL_INCOM_FWD_CALL";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_CALL_RESTRICTED:
			return "EVENT_CM_CALL_CALL_RESTRICTED";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_CUG_INFO_RECEIVED:
			return "EVENT_CM_CALL_CUG_INFO_RECEIVED";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_CNAP_INFO_RECEIVED:
			return "EVENT_CM_CALL_CNAP_INFO_RECEIVED";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_EMERGENCY_FLASHED:
			return "EVENT_CM_CALL_EMERGENCY_FLASHED";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_PROGRESS_INFO_IND:
			return "EVENT_CM_CALL_PROCESS_INFO_IND";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_CALL_DEFLECTION:
			return "EVENT_CM_CALL_CALL_DEFLECTION";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_TRANSFERRED_CALL:
			return "EVENT_CM_CALL_TRANSFERRED_CALL";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_EXIT_TC:
			return "EVENT_CM_CALL_EXIT_TC";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_REDIRECTING_NUMBER:
			return "EVENT_CM_CALL_REDIRECTING_NUMBER";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_PDP_PROMOTE_IND:
			return "EVENT_CM_CALL_PDP_PROMOTE_IND";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_UMTS_CDMA_HANDOVER_START:
			return "EVENT_CM_CALL_UMTS_CDMA_HANDOVER_START";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_UMTS_CDMA_HANDOVER_END:
			return "EVENT_CM_CALL_UMTS_CDMA_HANDOVER_END";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_SECONDARY_MSM:
			return "EVENT_CM_CALL_SECONDARY_MSM";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_ORIG_MOD_TO_SS:
			return "EVENT_CM_CALL_ORIG_MOD_TO_SS";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_USER_DATA_IND:
			return "EVENT_CM_CALL_USER_DATA_IND";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_USER_DATA_CONG_IND:
			return "EVENT_CM_CALL_USER_DATA_CONG_IND";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_MODIFY_IND:
			return "EVENT_CM_CALL_MODIFY_IND";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_MODIFY_REQ:
			return "EVENT_CM_CALL_MODIFY_REQ";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_LINE_CTRL:
			return "EVENT_CM_CALL_LINE_CTRL";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_CCBS_ALLOWED:
			return "EVENT_CM_CALL_CCBS_ALLOWED";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_ACT_CCBS_CNF:
			return "EVENT_CM_CALL_ACT_CCBS_CNF";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_CCBS_RECALL_IND:
			return "EVENT_CM_CALL_CCBS_RECALL_IND";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_CCBS_RECALL_RSP:
			return "EVENT_CM_CALL_CCBS_RECALL_RSP";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_CALL_ORIG_THR:
			return "EVENT_CM_CALL_CALL_ORIG_THR";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_VS_AVAIL:
			return "EVENT_CM_CALL_VS_AVAIL";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_VS_NOT_AVAIL:
			return "EVENT_CM_CALL_VS_NOT_AVAIL";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_MODIFY_COMPLETE_CONF:
			return "EVENT_CM_CALL_MODIFY_COMPLETE_CONF";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_MODIFY_RES:
			return "EVENT_CM_CALL_MODIFY_RES";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_CONNECT_ORDER_ACK:
			return "EVENT_CM_CALL_CONNECT_ORDER_ACK";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_TUNNEL_MSG:
			return "EVENT_CM_CALL_TUNNEL_MSG";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_END_VOIP_CALL:
			return "EVENT_CM_CALL_END_VOIP";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_VOIP_CALL_END_CNF:
			return "EVENT_CM_CALL_VOIP_CALL_END";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_PS_SIG_REL_REQ:
			return "EVENT_CM_CALL_PS_SIG_REL_REQ";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_PS_SIG_REL_CNF:
			return "EVENT_CM_CALL_PS_SIG_REL_CNF";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_CALL_PS_SIG_REL_IND:
			return "EVENT_CM_CALL_PS_SIG_REL_IND";

		case MSMCOMM_MESSAGE_TYPE_EVENT_SIM_INSERTED:
			return "EVENT_SIM_INSERTED";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SIM_PIN1_VERIFIED:
			return "EVENT_SIM_PIN1_VERIFIED";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SIM_PIN1_BLOCKED:
			return "EVENT_SIM_PIN1_BLOCKED";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SIM_PIN1_UNBLOCKED:
			return "EVENT_SIM_PIN1_UNBLOCKED";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SIM_PIN1_ENABLED:
			return "EVENT_SIM_PIN1_ENABLED";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SIM_PIN1_DISABLED:
			return "EVENT_SIM_PIN1_DISABLED";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SIM_PIN1_CHANGED:
			return "EVENT_SIM_PIN1_CHANGED";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SIM_PIN1_PERM_BLOCKED:
			return "EVENT_SIM_PIN1_PERM_BLOCKED";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SIM_PIN2_VERIFIED:
			return "EVENT_SIM_PIN2_VERIFIED";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SIM_PIN2_BLOCKED:
			return "EVENT_SIM_PIN2_BLOCKED";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SIM_PIN2_UNBLOCKED:
			return "EVENT_SIM_PIN2_UNBLOCKED";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SIM_PIN2_ENABLED:
			return "EVENT_SIM_PIN2_ENABLED";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SIM_PIN2_DISABLED:
			return "EVENT_SIM_PIN2_DISABLED";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SIM_PIN2_CHANGED:
			return "EVENT_SIM_PIN2_CHANGED";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SIM_PIN2_PERM_BLOCKED:
			return "EVENT_SIM_PIN2_PERM_BLOCKED";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SIM_REFRESH_RESET:
			return "EVENT_SIM_REFRESH_RESET";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SIM_REFRESH_INIT:
			return "EVENT_SIM_REFRESH_INIT";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SIM_REFRESH_INIT_FCN:
			return "EVENT_SIM_REFRESH_INIT_FCN";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SIM_REFRESH_FAILED:
			return "EVENT_SIM_REFRESH_FAILED";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SIM_FDN_ENABLE:
			return "EVENT_SIM_FDN_ENABLE";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SIM_FDN_DISABLE:
			return "EVENT_SIM_FDN_DISABLE";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SIM_ILLEGAL:
			return "EVENT_SIM_ILLEGAL";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SIM_ILLEGAL_2:
			return "EVENT_SIM_ILLEGAL_2";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SIM_UHZI_V2_COMPLETE:
			return "EVENT_SIM_UHZI_V2_COMPLETE";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SIM_UHZI_V1_COMPLETE:
			return "EVENT_SIM_UHZI_V1_COMPLETE";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SIM_PERSO_EVENT_GEN_PROP2:
			return "EVENT_SIM_PERSO_EVENT_GEN_PROP2";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SIM_REMOVED:
			return "EVENT_SIM_REMOVED";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SIM_NO_SIM_EVENT:
			return "EVENT_SIM_NO_SIM_EVENT";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SIM_NO_SIM:
			return "EVENT_SIM_NO_SIM";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SIM_DRIVER_ERROR:
			return "EVENT_SIM_DRIVER_ERROR";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SIM_INTERNAL_RESET:
			return "EVENT_SIM_INTERNAL_RESET";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SIM_OK_FOR_TERMINAL_PROFILE_DL:
			return "EVENT_SIM_OK_FOR_TERMINAL_PROFILE_DL";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SIM_NOT_OK_FOR_TERMINAL_PROFILE_DL:
			return "EVENT_SIM_NOT_OK_FOR_TERMINAL_PROFILE_DL";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SIM_INIT_COMPLETED_NO_PROV:
			return "EVENT_SIM_INIT_COMPLETED_NO_PROV";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SIM_MEMORY_WARNING:
			return "EVENT_SIM_MEMORY_WARNING";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SIM_SIM2_EVENT:
			return "EVENT_SIM_SIM2_EVENT";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SIM_REAL_RESET_FAILURE:
			return "EVENT_SIM_REAL_RESET_FAILURE";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SIM_CARD_ERROR:
			return "EVENT_SIM_CARD_ERROR";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SIM_NO_EVENT:
			return "EVENT_SIM_NO_EVENT";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SIM_GET_PERSO_NW_FAILURE:
			return "EVENT_SIM_GET_PERSO_NW_FAILURE";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SIM_GET_PERSO_NW_BLOCKED:
			return "EVENT_SIM_GET_PERSO_NW_BLOCKED";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SIM_REFRESH_APP_RESET:
			return "EVENT_SIM_REFRESH_APP_RESET";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SIM_REFRESH_3G_SESSION_RESET:
			return "EVENT_SIM_REFRESH_3G_SESSION_RESET";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SIM_APP_SELECTED:
			return "EVENT_SIM_APP_SELECTED";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SIM_DEFAULT:
			return "EVENT_SIM_DEFAULT";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SIM_CARD_ERR_NOT_ATR_RECEIVED_WITH_MAX_VOLTAGE:
			return "EVENT_SIM_CARD_ERR_NOT_ATR_RECEIVED_WITH_MAX_VOLTAGE";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SIM_APP_RESET:
			return "EVENT_SIM_APP_RESET";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SIM_3G_SESSION_RESET_2:
			return "EVENT_SIM_3G_SESSION_RESET_2";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SIM_PERSO_SANITY_ERROR:
			return "EVENT_SIM_PERSO_SANITY_ERROR";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SIM_PERSO_GEN_PROP1:
			return "EVENT_SIM_PERSO_GEN_PROP1";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SIM_PERSO_GEN_PROP2:
			return "EVENT_SIM_PERSO_GEN_PROP2";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SIM_PERSO_EVT_INIT_COMPLETED:
			return "EVENT_SIM_PERSO_EVT_INIT_COMPLETED";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SIM_PLMN_SEL_MENU_ENABLE:
			return "EVENT_SIM_PLMN_SEL_MENU_ENABLE";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SIM_PLMN_SEL_MENU_DISABLE:
			return "EVENT_SIM_PLMN_SEL_MENU_DISABLE";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SUPS_PROCESS_USS:
			return "EVENT_SUPS_PROCESS_USS";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SUPS_PROCESS_USS_CONF:
			return "EVENT_SUPS_PROCESS_USS_CONF";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SUPS_USS_RES:
			return "EVENT_SUPS_USS_RES";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SUPS_RELEASE_USS_IND:
			return "EVENT_SUPS_RELEASE_USS_IND";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SUPS_USS_NOTIFY_IND:
			return "EVENT_SUPS_USS_NOTIFY_IND";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SUPS_USS_NOTIFY_RES:
			return "EVENT_SUPS_USS_NOTIFY_RES";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SUPS_RELEASE:
			return "EVENT_SUPS_RELEASE";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SUPS_ABORT:
			return "EVENT_SUPS_ABORT";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SUPS_ERASE:
			return "EVENT_SUPS_ERASE";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SUPS_REGISTER:
			return "EVENT_SUPS_REGISTER";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SUPS_REGISTER_CONF:
			return "EVENT_SUPS_REGISTER_CONF";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SUPS_GET_PASSWORD_IN:
			return "EVENT_SUPS_GET_PASSWORD_IN";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SUPS_GET_PASSWORD_RES:
			return "EVENT_SUPS_GET_PASSWORD_RES";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SUPS_INTERROGATE:
			return "EVENT_SUPS_INTERROGATE";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SUPS_INTERROGATE_CONF:
			return "EVENT_SUPS_INTERROGATE_CONF";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SUPS_ACTIVATE:
			return "EVENT_SUPS_ACTIVATE";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SUPS_ACTIVATE_CONF:
			return "EVENT_SUPS_ACTIVATE_CONF";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SUPS_DEACTIVATE:
			return "EVENT_SUPS_DEACTIVATE";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SUPS_DEACTIVATE_CONF:
			return "EVENT_SUPS_DEACTIVATE_CONF";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SMS_WMS_CFG_MESSAGE_LIST:
			return "EVENT_SMS_WMS_CFG_MESSAGE_LIST";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SMS_WMS_CFG_GW_DOMAIN_PREF:
			return "EVENT_SMS_WMS_CFG_GW_DOMAIN_PREF";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SMS_WMS_CFG_EVENT_ROUTES:
			return "EVENT_SMS_WMS_CFG_EVENT_ROUTES";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SMS_WMS_CFG_MEMORY_STATUS:
			return "EVENT_SMS_WMS_CFG_MEMORY_STATUS";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SMS_WMS_CFG_MEMORY_STATUS_SET:
			return "EVENT_SMS_WMS_CFG_MEMORY_STATUS_SET";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SMS_WMS_CFG_GW_READY:
			return "EVENT_SMS_WMS_CFG_GW_READY";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SMS_RECEIVED_MESSAGE:
			return "EVENT_SMS_RECEIVED_MESSAGE";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SMS_WMS_READ_TEMPLATE:
			return "EVENT_SMS_WMS_READ_TEMPLATE";
		case MSMCOMM_MESSAGE_TYPE_EVENT_SMS_INFO:
			return "EVENT_SMS_INFO";
		case MSMCOMM_MESSAGE_TYPE_EVENT_PHONEBOOK_READY:
			return "EVENT_PHONEBOOK_READY";
		case MSMCOMM_MESSAGE_TYPE_EVENT_PHONEBOOK_MODIFIED:
			return "EVENT_PHONEBOOK_MODIFIED";
		case MSMCOMM_MESSAGE_TYPE_EVENT_PHONEBOOK_RECORD_ADDED:
			return "EVENT_PHONEBOOK_RECORD_ADDED";
		case MSMCOMM_MESSAGE_TYPE_EVENT_PHONEBOOK_RECORD_DELETED:
			return "EVENT_PHONEBOOK_RECORD_DELETED";
		case MSMCOMM_MESSAGE_TYPE_EVENT_PHONEBOOK_RECORD_UPDATED:
			return "EVENT_PHONEBOOK_RECORD_UPDATED";
		case MSMCOMM_MESSAGE_TYPE_EVENT_PHONEBOOK_RECORD_FAILED:
			return "EVENT_PHONEBOOK_RECORD_FAILED";
		case MSMCOMM_MESSAGE_TYPE_EVENT_CM_PH:
			return "EVENT_CM_PH";
		case MSMCOMM_MESSAGE_TYPE_EVENT_GET_NETWORKLIST:
			return "EVENT_GET_NETWORKLIST";
		case MSMCOMM_MESSAGE_TYPE_EVENT_PDSM_PD_DONE:
			return "EVENT_PDSM_PD_DONE";
		case MSMCOMM_MESSAGE_TYPE_EVENT_PDSM_XTRA:
			return "EVENT_PDSM_XTRA";
		default:
			return "<UNKNOWN>";
	}
}

char *msmcomm_message_class_to_string(msmcomm_message_class_t type)
{
	switch (type)
	{
		case MSMCOMM_MESSAGE_CLASS_NONE:
			return "CLASS_NONE";
		case MSMCOMM_MESSAGE_CLASS_COMMAND:
			return "CLASS_COMMAND";
		case MSMCOMM_MESSAGE_CLASS_RESPONSE:
			return "CLASS_RESPONSE";
		case MSMCOMM_MESSAGE_CLASS_EVENT:
			return "CLASS_EVENT";
		default:
			return "<UNKNOWN>";
	}
}
